#!/usr/bin/env bash
# One-shot Entire bootstrap.
#
# Run from the repo root:   bash scripts/setup_entire.sh
#
# Installs the CLI (idempotent), enables Entire on this repo, and
# captures a dispatch summary into docs/entire-dispatches/<date>.md.
# Re-run after every major commit so reasoning traces stay current.
#
# DISPATCH MODES:
#   server-side (default — no --local):  generated by Entire's server.
#                                        Requires `entire login` once.
#                                        Does NOT consume your local
#                                        Anthropic credit.
#   --local mode:                        generated by your locally-
#                                        installed Claude CLI.  Burns
#                                        Anthropic credit per run.
#                                        Pass ENTIRE_LOCAL=1 to opt in.
#
# If you saw "claude CLI error (kind=config): Credit balance is too low"
# from a previous run, that was --local mode hitting your depleted
# Anthropic balance.  Default (server mode) avoids that entirely — just
# run `entire login` once and the server does the LLM work for you.

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v entire >/dev/null 2>&1; then
  echo "→ Installing Entire CLI…"
  curl -fsSL https://entire.io/install.sh | bash
  export PATH="$HOME/.entire/bin:$PATH"
fi

echo "→ entire enable in $(pwd)"
entire enable || {
  echo "If this errored with 'already enabled', that's fine — proceeding."
}

DISPATCH_DIR="docs/entire-dispatches"
mkdir -p "$DISPATCH_DIR"
DATE_STAMP="$(date +%Y-%m-%d)"
DISPATCH_FILE="$DISPATCH_DIR/$DATE_STAMP.md"

# Default: server mode (no --local).  Opt into --local with
# ENTIRE_LOCAL=1 if your Anthropic credit is healthy and you want
# offline generation.
if [ "${ENTIRE_LOCAL:-0}" = "1" ]; then
  DISPATCH_FLAGS="--local --since 24h"
  MODE_DESC="local Claude CLI"
else
  DISPATCH_FLAGS="--since 24h"
  MODE_DESC="Entire server"
fi

echo "→ entire dispatch ${DISPATCH_FLAGS}  (mode: ${MODE_DESC} → ${DISPATCH_FILE})"

# Run dispatch.  If it fails with an auth error, prompt for `entire login`
# without recursing — we don't want infinite loops.
if entire dispatch ${DISPATCH_FLAGS} > "$DISPATCH_FILE.tmp" 2>&1; then
  mv "$DISPATCH_FILE.tmp" "$DISPATCH_FILE"
  echo "  → wrote $DISPATCH_FILE"
  echo
  echo "  Commit it next:"
  echo "      git add $DISPATCH_FILE && git commit -m 'entire: dispatch $DATE_STAMP'"
else
  RC=$?
  ERR_BODY="$(cat "$DISPATCH_FILE.tmp" 2>/dev/null || true)"
  rm -f "$DISPATCH_FILE.tmp"

  if echo "$ERR_BODY" | grep -qi "login\|unauthor\|forbidden\|401\|403"; then
    echo "  Note: server mode requires 'entire login' first.  Run:"
    echo "      entire login"
    echo "  …then re-run this script."
  elif echo "$ERR_BODY" | grep -qi "credit balance is too low"; then
    echo "  Note: --local mode hit your Anthropic credit cap.  Try server mode:"
    echo "      ENTIRE_LOCAL=0 bash scripts/setup_entire.sh"
    echo "      (after running 'entire login' if you haven't)"
  else
    echo "  Note: dispatch failed (exit $RC).  Recent output:"
    echo "$ERR_BODY" | tail -10 | sed 's/^/      /'
    echo "  May need a fresh commit since the last dispatch."
  fi
fi

echo
echo "Done.  Build journal lives at $DISPATCH_DIR/ — see README '## Build journal'."
